config/routes.rb
Rails.application.routes.draw do
  resources :exchanges
  resources :stocks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  validates_presence_of :name, :code

  has_many :stocks
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates_presence_of :name, :code

  belongs_to :exchange

  delegate :code, :name, to: :exchange, prefix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: %i[ show edit update destroy ]

  # GET /exchanges or /exchanges.json
  def index
    @exchanges = Exchange.all
  end

  # GET /exchanges/1 or /exchanges/1.json
  def show
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges or /exchanges.json
  def create
    @exchange = Exchange.new(exchange_params)

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to @exchange, notice: "Exchange was successfully created." }
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchanges/1 or /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to @exchange, notice: "Exchange was successfully updated." }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1 or /exchanges/1.json
  def destroy
    @exchange.destroy
    respond_to do |format|
      format.html { redirect_to exchanges_url, notice: "Exchange was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exchange_params
      params.require(:exchange).permit(:code, :name)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    if params[:codes]
      @stocks = Stock.where(code: params[:codes].split(","))
    else
      @stocks = Stock.all
    end
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:code, :name, :price, :exchange_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/exchanges/_form.html.erb
<%= form_with(model: exchange, local: true) do |form| %>
  <% if exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
        <% exchange.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to 'Show', @exchange %> |
<%= link_to 'Back', exchanges_path %>

app/views/exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exchanges</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchanges.each do |exchange| %>
      <tr>
        <td><%= exchange.code %></td>
        <td><%= exchange.name %></td>
        <td><%= link_to 'Show', exchange %></td>
        <td><%= link_to 'Edit', edit_exchange_path(exchange) %></td>
        <td><%= link_to 'Destroy', exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange', new_exchange_path %>

app/views/exchanges/new.html.erb
<h1>New Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to 'Back', exchanges_path %>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @exchange.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @exchange.name %>
</p>

<%= link_to 'Edit', edit_exchange_path(@exchange) %> |
<%= link_to 'Back', exchanges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Performance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :exchange_id %>
    <%= form.number_field :exchange_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Stock</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td>
          <%= stock.exchange_name %> (<%= stock.exchange_code %>)<br/>
          <h4><b><%= stock.code %></b> <%= stock.name %><h4>
        </td>
        <td><%= number_to_currency stock.price %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @stock.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @stock.price %>
</p>

<p>
  <strong>Exchange:</strong>
  <%= @stock.exchange_id %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>